name: learning
description: "CHL Color Picker"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cyclop: ^0.7.0
  snapping_sheet_2: ^3.1.5
  reorderable_grid_view: ^2.2.8
  image: ^4.0.0
  icc_parser: ^0.2.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - reference-icc/Canon ImagePROGRAPH PRO-1000.icc
    - assets/icons/

  fonts:
    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic-Thin.ttf
          weight: 100
        - asset: assets/fonts/Livvic-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Livvic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Livvic-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Livvic-Light.ttf
          weight: 300
        - asset: assets/fonts/Livvic-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Livvic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Livvic-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Livvic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Livvic-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Livvic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Livvic-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Livvic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Livvic-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Livvic-Black.ttf
          weight: 900
        - asset: assets/fonts/Livvic-BlackItalic.ttf
          weight: 900
          style: italic
